nutritional_tips = [
    "💧 Hidratación Estratégica: Bebe agua de forma constante a lo largo del día. La hidratación óptima es clave para la termorregulación, el transporte de nutrientes y la prevención de la fatiga metabólica.",
    "🌈 Diversidad Fitoquímica: Prioriza la variedad cromática en vegetales y frutas. Los colores vivos indican la presencia de fitoquímicos y antioxidantes con efectos protectores contra el daño celular.",
    "🏃‍♂️ Movimiento Diario Mínimo: Incorpora un mínimo de 30 minutos de movimiento moderado o 10,000 pasos al día. Esto mejora la sensibilidad a la insulina y optimiza la composición corporal.",
    "🧂 Control del Sodio: Limita la ingesta de alimentos ultraprocesados, que son la principal fuente de sodio añadido. Utiliza hierbas y especias como potenciadores de sabor, favoreciendo el control de la presión arterial.",
    "🛌 Prioridad al Sueño: Asegura 7-9 horas de sueño reparador. La privación del sueño afecta negativamente a las hormonas grelina y leptina, dificultando el control del apetito y la gestión del peso.",
    "🥩 Densidad Nutricional Proteica: Incluye una fuente de proteína de alto valor biológico en cada comida. Esto maximiza la saciedad, ayuda a preservar la masa muscular y tiene un alto efecto termogénico.",
    "📋 Planeación Estratégica: La planificación semanal de comidas (meal prep) elimina las decisiones alimentarias por impulso, siendo fundamental para mantener la adherencia a cualquier objetivo dietético.",
    "⚖️ Enfoque en la Sostenibilidad: La adherencia a largo plazo supera a la perfección a corto plazo. Prioriza hábitos realistas y sostenibles sobre dietas restrictivas y temporales.",
    "⚡ Reposición Post-Entrenamiento: Consumir una combinación de carbohidratos y proteínas después del ejercicio (ej., plátano con suero) acelera la resíntesis de glucógeno y la reparación de fibras musculares.",
    "🧠 Conexión Intestino-Cerebro: Una nutrición adecuada, rica en fibra y micronutrientes, modula la microbiota intestinal, lo que está directamente relacionado con la función cognitiva y el estado de ánimo.",
    "🚫 Eliminación de Azúcares Líquidos: Las bebidas azucaradas aportan calorías vacías que no generan saciedad. Sustitúyelas por agua, café solo o infusiones para reducir drásticamente tu consumo calórico diario.",
    "🍳 Desayuno Estructural: Inicia tu día con una comida rica en proteínas y grasas saludables (ej., huevos, yogur natural). Esto estabiliza los niveles de glucosa y retrasa la aparición de hambre.",
    "🥜 Grasas Funcionales: Un consumo moderado de frutos secos (almendras, nueces) proporciona ácidos grasos esenciales (Omega-3), vitamina E y fibra, siendo un excelente snack cardioprotector.",
    "📱 Rastreo y Conciencia: El registro de alimentos (tracking) es una herramienta poderosa. Aumenta la conciencia calórica y macronutricional, permitiendo ajustes precisos basados en datos objetivos.",
    "🍎 Prioridad a la Comida Real: Escoge alimentos en su estado natural o mínimamente procesado. Los alimentos frescos son más densos en nutrientes y carecen de aditivos y grasas trans indeseadas.",
    "🥳 Flexibilidad Metabólica: La moderación y el disfrute consciente (regla 80/20) son vitales para la salud mental y la adherencia. No hay alimentos prohibidos, sino patrones dietéticos desequilibrados.",
    "💪 Optimización Hipertrófica: Si tu objetivo es la ganancia de músculo (hipertrofia), eleva tu ingesta proteica a 1.6 - 2.2 gramos de proteína por kg de peso corporal para maximizar la síntesis proteica muscular (MPS).",
    "🔎 Alfabetización Nutricional: Domina la lectura de etiquetas. Presta atención a la lista de ingredientes y a la cantidad de azúcares añadidos y grasas saturadas por porción.",
    "🍽 Alimentación Consciente: Come sin distracciones y mastica lentamente. La alimentación consciente (mindful eating) mejora la señalización de saciedad al cerebro, optimizando la digestión.",
    "📊 Adecuación Energética: Ajusta tu ingesta calórica y macronutricional a tu gasto energético total (GET). Los requerimientos de un día de entrenamiento intenso son diferentes a los de un día de descanso."
]
